Program pdfgetindex v0.1

diff --git a/pdfgetindex b/pdfgetindex
--- a/pdfgetindex
+++ b/pdfgetindex
@@ -1,7 +1,80 @@
 #!/bin/sh
+#
+# Retrieves the indexes of a pdf. The Output is intended to be used
+# with pdfindex
+#
+# v0.1: First version; options -v, -h
+
+VERSION="0.1"
+USAGE="USAGE: pdfgetindex <options> <pdffile>"
+
+
+while getopts ":hv" opt
+do
+	case $opt in
+		h)
+			echo "$USAGE";
+			exit 0
+			;;
+		v)
+			echo "Version: $(basename $0) $VERSION";
+			exit 0
+			;;
+		\?)
+			# Unknown Option
+			echo "EOR: Unknown opt -$OPTARG"
+			exit 1
+			;;
+		:)
+			# Missing Argument
+			echo "ERROR: Missing argument for opt: -$OPTARG"
+			exit 1;
+			;;
+	esac
+done
+shift $((OPTIND-1))
+
+pdftk --help > /dev/null
+
+if [ "$?" -ne "0" ]; then
+	echo "ERROR: pdftk not found"
+	exit 1
+fi
+
+if [ -z "$1" ];
+then
+	echo "ERROR: Missing first argument"
+	echo "$USAGE"
+	exit 1
+fi
+
+if [ ! -e "$1" ];
+then
+	echo "ERROR: File \"$1\" does not exist"
+	exit 1
+fi
+
+if [ ! -r "$1" ];
+then
+	echo "ERROR: File \"$1\" does not have read permissions"
+	exit 1
+fi
+
 PDF=$1
-#FILE=$(cat bookmarks.txt )
-FILE=$(pdftk $PDF dump_data_utf8 | grep "^Bookmark")
+MIME=$(xdg-mime query filetype "$PDF" )
+
+if [ "$MIME" != "application/pdf" ];
+then
+	echo "ERROR: $PDF is not a pdf file"
+	exit 1
+fi
+
+FILE=$(pdftk "$PDF" dump_data_utf8 | grep "^Bookmark")
+
+if [ -z "$FILE" ]; then
+	echo "ERROR: $PDF has no indexes"
+	exit 0;
+fi
 
 while read line
 do
@@ -47,11 +120,13 @@ done <<< "$ARRAY"
 
 CHAPTERS=$(echo -e "${CHAPTERS#\\n}")
 
-while read line
-do
-	LN=${line%%:*}
-	REC=${line##*:}
-	ARRAY=$(echo "$ARRAY" | sed "${LN}s/^/p:$REC:/")
-done <<< "$CHAPTERS"
+if [ -n "$CHAPTERS" ]; then
+	while read line
+	do
+		LN=${line%%:*}
+		REC=${line##*:}
+		ARRAY=$(echo "$ARRAY" | sed "${LN}s/^/p:$REC:/")
+	done <<< "$CHAPTERS"
+fi
 
-echo "$ARRAY"
+echo "$ARRAY" | sed -E "s/:[0-9]+$//g"
